name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Jacob Tomlinson"
inputs:
  token:
    description: "The Personal Token"
    required: true
  project_number:
    description: "The Project Number"
    required: true
  duedate_field_name:
    description: "The field name"
    required: false
  notification_type:
    description: "The type of notification (comment,aws_email)"
    default: 'aws_email'
#outputs:
#  myOutput:
#    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
